PLUGIN_NAME=tincdcustom
PLUGIN_VERSION=0.7.4
PLUGIN_COMMENT=opnsense tincd - custom configuration enabled
PLUGIN_MAINTAINER=eugen.mayer@kontextwork.de
PLUGIN_DEPENDS=tinc
.include "../../Mk/plugins.mk"